#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  Jun 08, 2023 08:04:08 AM CDT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set desc "-family {DejaVu Sans} -size 10"
set vTcl(actual_gui_font_dft_desc) $desc
set vTcl(actual_gui_font_dft_name) [font create {*}$desc]
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #d9d9d9
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m65" -background $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 981x661+619+156
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2545 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Style Module Demo"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    labelframe "$top.lab47" \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -text "Tk Standard Widgets" \
        -background $vTcl(actual_gui_bg) -height 265 -highlightcolor black \
        -width 960 
    vTcl:DefineAlias "$top.lab47" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.lab47
    labelframe "$site_3_0.lab57" \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -text "Tk Checkbuttons" \
        -background $vTcl(actual_gui_bg) -height 75 -highlightcolor black \
        -width 150 
    vTcl:DefineAlias "$site_3_0.lab57" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_4_0 $site_3_0.lab57
    checkbutton "$site_4_0.che58" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -selectcolor #d9d9d9 -text "Check" -variable "che58" 
    vTcl:DefineAlias "$site_4_0.che58" "Checkbutton3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    checkbutton "$site_4_0.che59" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -selectcolor #d9d9d9 -text "Check" -variable "che59" 
    vTcl:DefineAlias "$site_4_0.che59" "Checkbutton4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    checkbutton "$site_4_0.che60" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -selectcolor #d9d9d9 -text "Check" -variable "che60" 
    vTcl:DefineAlias "$site_4_0.che60" "Checkbutton5" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_4_0.che58 \
        -in $site_4_0 -x 20 -y 30 -width 144 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.che59 \
        -in $site_4_0 -x 20 -y 70 -width 144 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.che60 \
        -in $site_4_0 -x 20 -y 110 -width 144 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe "$site_3_0.lab61" \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -text "Tk Radiobuttons" \
        -background $vTcl(actual_gui_bg) -height 75 -highlightcolor black \
        -width 150 
    vTcl:DefineAlias "$site_3_0.lab61" "Labelframe3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_4_0 $site_3_0.lab61
    radiobutton "$site_4_0.rad62" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -selectcolor #d9d9d9 -text "Radio" -value "1" \
        -variable "selectedButton" 
    vTcl:DefineAlias "$site_4_0.rad62" "Radiobutton1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    radiobutton "$site_4_0.rad63" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -selectcolor #d9d9d9 -text "Radio" -value "2" \
        -variable "selectedButton" 
    vTcl:DefineAlias "$site_4_0.rad63" "Radiobutton2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    radiobutton "$site_4_0.rad64" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -selectcolor #d9d9d9 -text "Radio" -value "3" \
        -variable "selectedButton" 
    vTcl:DefineAlias "$site_4_0.rad64" "Radiobutton3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_4_0.rad62 \
        -in $site_4_0 -x 10 -y 30 -width 144 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.rad63 \
        -in $site_4_0 -x 10 -y 70 -width 144 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.rad64 \
        -in $site_4_0 -x 10 -y 110 -width 144 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe "$site_3_0.lab78" \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -text "Other Tk widgets" \
        -background $vTcl(actual_gui_bg) -height 225 -highlightcolor black \
        -width 540 
    vTcl:DefineAlias "$site_3_0.lab78" "Labelframe4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_4_0 $site_3_0.lab78
    entry "$site_4_0.ent79" \
        -background white -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 146 
    vTcl:DefineAlias "$site_4_0.ent79" "Entry1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$site_4_0.lab80" \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text "Tk Entry" 
    vTcl:DefineAlias "$site_4_0.lab80" "Label1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    message "$site_4_0.mes81" \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -font "-family {DejaVu Sans} -size 10" \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -padx 1 \
        -pady 1 -relief groove -text "Message" -width 112 
    vTcl:DefineAlias "$site_4_0.mes81" "Message1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    scale "$site_4_0.sca82" \
        -activebackground $vTcl(analog_color_m) \
        -background $vTcl(actual_gui_bg) -bigincrement 0.0 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -from 0.0 -highlightcolor black \
        -length 100 -orient horizontal -resolution 1.0 -tickinterval 0.0 \
        -to 100.0 -troughcolor #d9d9d9 
    vTcl:DefineAlias "$site_4_0.sca82" "Scale1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    spinbox "$site_4_0.spi83" \
        -activebackground #f9f9f9 -background white \
        -font "-family {DejaVu Sans} -size 10" -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -to 100.0 
    vTcl:DefineAlias "$site_4_0.spi83" "Spinbox1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    listbox "$site_4_0.lis84" \
        -background white -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -height 56 -highlightcolor black \
        -selectbackground #c4c4c4 -selectforeground black -width 114 
    $site_4_0.lis84 configure -font "TkFixedFont"
    $site_4_0.lis84 insert end text
    vTcl:DefineAlias "$site_4_0.lis84" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    text "$site_4_0.tex85" \
        -background white -font "TkTextFont" -foreground black -height 54 \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 116 \
        -wrap word 
    $site_4_0.tex85 configure -font "TkTextFont"
    $site_4_0.tex85 insert end text
    vTcl:DefineAlias "$site_4_0.tex85" "Text1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$site_4_0.lab86" \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text "Tk Message" 
    vTcl:DefineAlias "$site_4_0.lab86" "Label2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$site_4_0.lab87" \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text "Tk Listbox" 
    vTcl:DefineAlias "$site_4_0.lab87" "Label3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$site_4_0.lab88" \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text "Tk Scale" 
    vTcl:DefineAlias "$site_4_0.lab88" "Label4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$site_4_0.lab89" \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text "Tk Spinbox" 
    vTcl:DefineAlias "$site_4_0.lab89" "Label5" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$site_4_0.lab90" \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text "Tk Text widget" 
    vTcl:DefineAlias "$site_4_0.lab90" "Label6" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_4_0.ent79 \
        -in $site_4_0 -x 20 -y 50 -width 146 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab80 \
        -in $site_4_0 -x 20 -y 24 -width 69 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.mes81 \
        -in $site_4_0 -x 210 -y 50 -width 112 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.sca82 \
        -in $site_4_0 -x 20 -y 120 -anchor nw -bordermode ignore 
    place $site_4_0.spi83 \
        -in $site_4_0 -x 160 -y 140 -width 78 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lis84 \
        -in $site_4_0 -x 350 -y 40 -width 114 -relwidth 0 -height 56 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tex85 \
        -in $site_4_0 -x 350 -y 140 -width 116 -relwidth 0 -height 54 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab86 \
        -in $site_4_0 -x 210 -y 21 -width 102 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab87 \
        -in $site_4_0 -x 370 -y 20 -width 101 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab88 \
        -in $site_4_0 -x 20 -y 103 -width 99 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab89 \
        -in $site_4_0 -x 160 -y 103 -width 89 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab90 \
        -in $site_4_0 -x 340 -y 106 -width 129 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 10 -y 30 -width 200 -relwidth 0 -height 165 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 212 -y 30 -width 200 -relwidth 0 -height 165 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab78 \
        -in $site_3_0 -x 413 -y 30 -width 540 -relwidth 0 -height 225 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.lab47
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe "$top.tLa48" \
        -text "Ttk Themed Widgets" -width 150 -height 75 
    vTcl:DefineAlias "$top.tLa48" "TLabelframe1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.tLa48
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe "$site_3_0.tLa48" \
        -text "TCheckButtons" -width 200 -height 165 
    vTcl:DefineAlias "$site_3_0.tLa48" "TLabelframe2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_4_0 $site_3_0.tLa48
    ttk::style configure TCheckbutton -background $vTcl(actual_gui_bg)
    ttk::style configure TCheckbutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TCheckbutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::checkbutton "$site_4_0.tCh49" \
        -variable "tch49" -takefocus {} -text "Tcheck" -compound left 
    vTcl:DefineAlias "$site_4_0.tCh49" "TCheckbutton1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TCheckbutton -background $vTcl(actual_gui_bg)
    ttk::style configure TCheckbutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TCheckbutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::checkbutton "$site_4_0.tCh50" \
        -variable "tch50" -takefocus {} -text "Tcheck" -compound left 
    vTcl:DefineAlias "$site_4_0.tCh50" "TCheckbutton2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TCheckbutton -background $vTcl(actual_gui_bg)
    ttk::style configure TCheckbutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TCheckbutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::checkbutton "$site_4_0.tCh51" \
        -variable "tch51" -takefocus {} -text "Tcheck" -compound left 
    vTcl:DefineAlias "$site_4_0.tCh51" "TCheckbutton3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_4_0.tCh49 \
        -in $site_4_0 -x 20 -y 30 -width 144 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tCh50 \
        -in $site_4_0 -x 20 -y 70 -width 144 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tCh51 \
        -in $site_4_0 -x 20 -y 110 -width 144 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe "$site_3_0.tLa52" \
        -text "TRadiobuttons" -width 200 -height 165 
    vTcl:DefineAlias "$site_3_0.tLa52" "TLabelframe3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_4_0 $site_3_0.tLa52
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton "$site_4_0.tRa53" \
        -variable "TselectedButton" -text "TRadio" -compound left 
    vTcl:DefineAlias "$site_4_0.tRa53" "TRadiobutton1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton "$site_4_0.tRa54" \
        -variable "TselectedButton" -value "2" -text "TRadio" -compound left 
    vTcl:DefineAlias "$site_4_0.tRa54" "TRadiobutton2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton "$site_4_0.tRa55" \
        -variable "TselectedButton" -value "3" -text "TRadio" -compound left 
    vTcl:DefineAlias "$site_4_0.tRa55" "TRadiobutton3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_4_0.tRa53 \
        -in $site_4_0 -x 20 -y 30 -width 144 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tRa54 \
        -in $site_4_0 -x 20 -y 70 -width 144 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tRa55 \
        -in $site_4_0 -x 20 -y 110 -width 144 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe "$site_3_0.tLa68" \
        -text "Other ttk widgets" -width 540 -height 245 
    vTcl:DefineAlias "$site_3_0.tLa68" "TLabelframe4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_4_0 $site_3_0.tLa68
    ttk::combobox "$site_4_0.tCo69" \
        -font "TkTextFont" -textvariable "combobox" -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo69" "TCombobox1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::entry "$site_4_0.tEn70" \
        -font "TkTextFont" -foreground {} -background {} -takefocus {} \
        -cursor xterm 
    vTcl:DefineAlias "$site_4_0.tEn70" "TEntry1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::label "$site_4_0.tLa71" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10" -relief flat -anchor w \
        -justify left -text "TCombo" -compound left 
    vTcl:DefineAlias "$site_4_0.tLa71" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::label "$site_4_0.tLa72" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10" -relief flat -anchor w \
        -justify left -text "TEntry" -compound left 
    vTcl:DefineAlias "$site_4_0.tLa72" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::progressbar "$site_4_0.tPr73" \
        -length 150 -mode indeterminate 
    vTcl:DefineAlias "$site_4_0.tPr73" "TProgressbar1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::label "$site_4_0.tLa75" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10" -relief flat -anchor w \
        -justify left -text "TProgressbar" -compound left 
    vTcl:DefineAlias "$site_4_0.tLa75" "TLabel3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::scale "$site_4_0.tSc76" \
        -length 130 -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tSc76" "TScale1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::spinbox "$site_4_0.tSp77" \
        -from 1 -to 100 -font "TkTextFont" -foreground {} -background white \
        -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tSp77" "TSpinbox1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::label "$site_4_0.tLa91" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10" -relief flat -anchor w \
        -justify left -text "TScale" -compound left 
    vTcl:DefineAlias "$site_4_0.tLa91" "TLabel4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::label "$site_4_0.tLa92" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "-family {DejaVu Sans} -size 10" -relief flat -anchor w \
        -justify left -text "TSpinbox" -compound left 
    vTcl:DefineAlias "$site_4_0.tLa92" "TLabel5" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_4_0.tCo69 \
        -in $site_4_0 -x 20 -y 55 -width 137 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tEn70 \
        -in $site_4_0 -x 180 -y 54 -width 134 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tLa71 \
        -in $site_4_0 -x 30 -y 31 -width 96 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tLa72 \
        -in $site_4_0 -x 180 -y 31 -width 94 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tPr73 \
        -in $site_4_0 -x 340 -y 57 -width 150 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tLa75 \
        -in $site_4_0 -x 350 -y 31 -width 122 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tSc76 \
        -in $site_4_0 -x 30 -y 139 -width 130 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tSp77 \
        -in $site_4_0 -x 190 -y 138 -width 145 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tLa91 \
        -in $site_4_0 -x 30 -y 112 -width 112 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tLa92 \
        -in $site_4_0 -x 200 -y 112 -width 82 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa48 \
        -in $site_3_0 -x 10 -y 30 -width 200 -relwidth 0 -height 165 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa52 \
        -in $site_3_0 -x 212 -y 30 -width 200 -relwidth 0 -height 165 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa68 \
        -in $site_3_0 -x 414 -y 30 -width 540 -relwidth 0 -height 245 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.tLa48
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$top.tBu49" \
        -command "on_btnExit" -takefocus {} -text "Exit" -compound left 
    vTcl:DefineAlias "$top.tBu49" "btnExit" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    checkbutton "$top.che50" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -command "on_chk1" \
        -compound left -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -selectcolor #d9d9d9 -text "Show The Surprise" -variable "che50" 
    vTcl:DefineAlias "$top.che50" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    checkbutton "$top.che56" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) \
        -command "on_disableWidgets" -compound left \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -selectcolor #d9d9d9 -text "Disable Widgets" -variable "che56" 
    vTcl:DefineAlias "$top.che56" "Checkbutton2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    menu "$top.m65" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font "TkMenuFont" -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    
set site_3_0 $top.m65
    $top.m65 add cascade \
        -menu "$top.m65.men66" -compound left -label "File" 
    menu "$site_3_0.men66" \
        -activebackground beige -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    $site_3_0.men66 add command \
        -command "#" -compound left -label "New" 
    $site_3_0.men66 add command \
        -command "#" -compound left -label "Open" 
    $site_3_0.men66 add separator \
        
    $site_3_0.men66 add command \
        -command "#on_mnuFileExit" -compound left -label "Exit" 
    
set site_3_0 $top.m65
    $top.m65 add cascade \
        -menu "$top.m65.men67" -compound left -label "Help" 
    menu "$site_3_0.men67" \
        -activebackground beige -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    $site_3_0.men67 add command \
        -command "#" -compound left -label "About" 
    $site_3_0.men67 add separator \
        
    $site_3_0.men67 add command \
        -command "#" -compound left -label "Help" 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab47 \
        -in $top -x 10 -y 50 -width 960 -relwidth 0 -height 265 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa48 \
        -in $top -x 10 -y 330 -width 960 -relwidth 0 -height 285 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu49 \
        -in $top -x 870 -y 10 -width 83 -relwidth 0 -height 38 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.che50 \
        -in $top -x 30 -y 10 -width 167 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.che56 \
        -in $top -x 250 -y 10 -width 157 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

